plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - 2_Reflecting-on-Practice.md
  - Session-2-Facilitator-Qs.md
  - 3_Data-Feminism-Part-2.md
  - Session-3-Facilitator-Qs.md
  - bias_research_list.md
